---
title: "Index"
author: "Francisco Alvarez"
format: html
editor: visual
---

# ¿Qué es Basilea III?

Los Acuerdos de Basilea III, mejor conocidos como “Basilea III”, se refieren a un conjunto de propuestas de reforma de la regulación bancaria, publicadas a partir del 16 de diciembre de 2010. El Comité de Supervisión Bancaria de Basilea (con sede en la ciudad de Basilea, Suiza) es la principal organización en materia regulación y supervisión bancaria, cuyo objetivo principal es el de mejorar la estabilidad financiera a nivel mundial. El Comité está compuesto, actualmente, por 28 jurisdicciones de todo el mundo representados por miembros de la autoridad supervisora de cada sistema bancario. México actualmente es miembro y es representado institucionalmente por la Comisión Nacional Bancaria y de Valores (CNVB) y el Banco de México. Basilea III es entonces la tercera generación de acuerdos de regulación bancaria adoptados por el Comité de Supervisión Bancaria de Basilea y surgen como una respuesta a la crisis financiera de 2007-2009. El objetivo de estos acuerdos es reforzar la regulación, la supervisión y la gestión de riesgo de los bancos. Las medidas de Basilea III constituyen mínimos aplicables a bancos con actividad internacional y los miembros se comprometen a implementar y aplicar las normas en sus jurisdicciones nacionales.

# ¿Qué medidas contempla Basilea III?

## Capital

El acuerdo de Basilea III propone a los bancos aumentar sus reservas de capital para protegerse de posibles caídas. El capital mínimo de calidad (CET1), incluye las acciones ordinarias y los resultados acumulados. El ratio de capital CET1 pasa del 2% al 4,5%, computado sobre el total de los "activos ponderados por riesgo". Esta ratio de capital mínimo debe ser mantenido en todo momento por el banco y es uno de los más importantes. (Capital Mínimo de Calidad 1)/(Activos Ponderados por Riesgo)≤4.5% El llamado Capital Tier 1 incluye, además de las acciones comunes y las utilidades retenidas, las participaciones preferentes, híbridos de capital y deuda sin pagar. En suma, el ratio mínimo de Capital Total (que incluye el Capital Tier 1, más el denominado Capital Tier 2), asciende en total al 8% de los activos ponderados por riesgo. Respecto de los "activos ponderados por riesgo", se definen como la suma de los activos del banco, ponderados según el riesgo que cada activo comporte de acuerdo con las directrices de Basilea III. Por ejemplo: un préstamo al consumo, sin ninguna garantía, tiene un peso del 100%; mientras que un bono del estado, generalmente tiene un peso del 0%.

## Liquidez

Uno de los planes más importantes de la reforma de Basilea III es la introducción de dos ratios de liquidez: el LCR (Liquidity Coverage Ratio) y el NSFR (Net Stable Funding Ratio). El LCR (Coeficiente de Cobertura de Liquidez) es una relación de un mes, que tiene como objetivo requerir a los bancos mantener suficientes activos líquidos de alta calidad para cubrir las salidas netas de efectivo durante un período de 30 días. Su fundamento es el siguiente: los activos líquidos de los que dispone una institución financiera (por ejemplo, bonos gubernamentales y bonos corporativos) deben tener un valor mayor o igual que las salidas potenciales de efectivo (por ejemplo, pagarés que expiran y retiros de cuentas de depósito) de dicha institución. De manera matemática, esto es: (Activos Líquidos)/(Salidas Netas de Efectivo)≥100% El NSFR (Coeficiente de Fondeo Estable Neto) es una relación de un año que tiene como objetivo permitir a los bancos resistir un año a una crisis específica de la institución. Establece que el importe de los requisitos de recursos estables (financiación necesaria estable) debe ser menor que la cantidad de recursos disponibles (financiación estable disponible). Financiación Estable Necesaria\<Financiación Estable Disponible Basilea III en México Integración del Capital En México el capital neto está integrado por una parte básica y una parte complementaria, con la parte básica se integrada por capital básico 1 y capital básico 2.

${(Activos Líquidos)\over(Salidas Netas de Efectivo)}≥100%$

Alertas tempranas Un Banco podrá entrar en el esquema de alertas tempranas si incumple al menos una de las siguientes condiciones:

La CNBV clasificará a las instituciones en categorías (de la I a la V), para efectos de la instrumentación de medidas correctivas conforme a lo siguiente:

Wikipedia contributors. (s/f). Basilea III. Wikipedia, The Free Encyclopedia. https://es.wikipedia.org/w/index.php?title=Basilea_III&oldid=164723250 (S/f). Gob.mx. https://www.cnbv.gob.mx/Documents/Basilea%203%20en%20M%C3%A9xico%20(v16).pdf Basel Committee membership. (2013, junio 10). Bis.org. https://www.bis.org/bcbs/membership.htm

